Update clap
lagonapp/lagon pull request #159
Opened 2022-10-01 06:09 UTC by G3root

## About

fixes #157

2022-10-01 07:24 UTC, QuiiBz requested changes
Thanks for the PR! Just a wording change and we'll ready to merge/

2022-10-01 07:24 UTC, QuiiBz commented on .changeset/silent-shrimps-dance.md
> +update clap to v4
Could you capitalize `update`?

2022-10-01 07:24 UTC, QuiiBz commented on packages/cli/src/main.rs
> +#[command(author, version, about, long_about = None, arg_required_else_help = true)]
Happy to see only one change, I expected more than that.

2022-10-03 07:23 UTC, QuiiBz approved these changes
LGTM, thanks a lot!

2022-10-03 07:23 UTC, merged

2022-10-03 07:51 UTC, G3root commented
> LGTM, thanks a lot!

open some good first issues, i'll help with some.