feat(examples,docs): add Sidra example
lagonapp/lagon pull request #914
Opened 2023-06-01 08:10 UTC by barbarbar338

This PR adds [Sidra](https://npmjs.com/sidra) example.

2023-06-01 16:13 UTC, QuiiBz requested changes
Thanks! Could you also run `pnpm changeset` at the root of the repo and select the sidra example + the docs to add this change to their respective changelog?

2023-06-01 16:13 UTC, QuiiBz commented on examples/sidra/package.json
> +{
Please follow the structure with `name`, `version`, `private`, & `lagon-dev` script

2023-06-01 16:41 UTC, barbarbar338 commented
I guess this is okay rn :)

2023-06-01 17:07 UTC, QuiiBz approved these changes
LGTM, thanks!

2023-06-02 06:59 UTC, QuiiBz commented
I'm reverting https://github.com/lagonapp/lagon/pull/914/commits/5f8c801e0fe590b94e56fc6b5c619f7e945902e3, the version of PNPM hasn't been updated.

2023-06-02 07:12 UTC, QuiiBz approved these changes

2023-06-02 07:12 UTC, merged